Importing the Libraries

In [1]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv(r'\Users\User\Documents\housing.csv')

In [3]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [5]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Data Preparation

In [6]:
df.total_bedrooms = df.total_bedrooms.fillna(0)

In [7]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

Data Preparation

New Columns

In [8]:
df['rooms_per_household']= df['total_rooms'].div(df['households'].values)

In [9]:
df['bedrooms_per_room'] = df['total_bedrooms'].div(df['total_rooms'].values)
df['population_per_household'] =df['population'].div(df['households'].values)

In [10]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,bedrooms_per_room,population_per_household
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127,0.146591,2.555556
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137,0.155797,2.109842
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136,0.129516,2.802260
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352,0.184458,2.547945
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853,0.172096,2.181467
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,5.045455,0.224625,2.560606
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,6.114035,0.215208,3.122807
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,5.205543,0.215173,2.325635
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,5.329513,0.219892,2.123209
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,5.254717,0.221185,2.616981

Question 1

What is the most frequent observation (mode) for the column ocean_proximity?

In [11]:
df.ocean_proximity.mode()

0    <1H OCEAN
Name: ocean_proximity, dtype: object

In [12]:
df.ocean_proximity.value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

Question 2

Create the correlation matrix for the numerical features of your train dataset.

In a correlation matrix, you compute the correlation coefficient between every pair of features in the dataset.

What are the two features that have the biggest correlation in this dataset?

In [13]:
numerical = ['longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','rooms_per_household','bedrooms_per_room','population_per_household']

In [14]:
df[numerical].head().corr()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,rooms_per_household,bedrooms_per_room,population_per_household
longitude,1.000000,0.617647,-0.917392,0.715073,0.680394,0.696536,0.695699,0.874368,0.126297,-0.500562,-0.261918
latitude,0.617647,1.000000,-0.431714,-0.010209,-0.027916,-0.023703,-0.008673,0.656308,0.059829,-0.314265,0.012546
housing_median_age,-0.917392,-0.431714,1.000000,-0.896516,-0.886821,-0.891087,-0.896126,-0.660769,0.231094,0.155935,0.574451
total_rooms,0.715073,-0.010209,-0.896516,1.000000,0.997312,0.998329,0.997956,0.396761,-0.274552,-0.031386,-0.662171
total_bedrooms,0.680394,-0.027916,-0.886821,0.997312,1.000000,0.998641,0.999762,0.349382,-0.342901,0.041433,-0.700788
population,0.696536,-0.023703,-0.891087,0.998329,0.998641,1.000000,0.999013,0.385057,-0.314747,0.013163,-0.663181
households,0.695699,-0.008673,-0.896126,0.997956,0.999762,0.999013,1.000000,0.368909,-0.335186,0.028808,-0.693392
median_income,0.874368,0.656308,-0.660769,0.396761,0.349382,0.385057,0.368909,1.000000,0.366751,-0.643165,0.218802
rooms_per_household,0.126297,0.059829,0.231094,-0.274552,-0.342901,-0.314747,-0.335186,0.366751,1.000000,-0.919719,0.691538
bedrooms_per_room,-0.500562,-0.314265,0.155935,-0.031386,0.041433,0.013163,0.028808,-0.643165,-0.919719,1.000000,-0.472671
population_per_household,-0.261918,0.012546,0.574451,-0.662171,-0.700788,-0.663181,-0.693392,0.218802,0.691538,-0.472671,1.000000

Answer: 

Population and Household

Make median_house_value binary

In [15]:
mean_value =df.median_house_value.mean()

In [16]:
mean_value

206855.81690891474

In [17]:
df['above_average']=[1 if x >mean_value else 0 for x in df['median_house_value']]

In [18]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,bedrooms_per_room,population_per_household,above_average
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127,0.146591,2.555556,1
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137,0.155797,2.109842,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136,0.129516,2.802260,1
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352,0.184458,2.547945,1
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853,0.172096,2.181467,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,5.045455,0.224625,2.560606,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,6.114035,0.215208,3.122807,0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,5.205543,0.215173,2.325635,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,5.329513,0.219892,2.123209,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,5.254717,0.221185,2.616981,0

Data Splitting Train,Val,Test

Split your data in train/val/test sets, with 60%/20%/20% distribution.

Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.

Make sure that the target value (median_house_value) is not in your dataframe.

In [19]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

In [20]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [21]:
len(df_train), len(df_val), len(df_test)

(12384, 4128, 4128)

In [22]:
# Resetting index of the 3 datasets 
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [23]:
df_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,bedrooms_per_room,population_per_household,above_average
0,-119.67,34.43,39.0,1467.0,381.0,1404.0,374.0,2.3681,241400.0,<1H OCEAN,3.922460,0.259714,3.754011,1
1,-118.32,33.74,24.0,6097.0,794.0,2248.0,806.0,10.1357,500001.0,NEAR OCEAN,7.564516,0.130228,2.789082,1
2,-121.62,39.13,41.0,1317.0,309.0,856.0,337.0,1.6719,64100.0,INLAND,3.908012,0.234624,2.540059,0
3,-118.63,34.24,9.0,4759.0,924.0,1884.0,915.0,4.8333,277200.0,<1H OCEAN,5.201093,0.194158,2.059016,1
4,-122.30,37.52,38.0,2769.0,387.0,994.0,395.0,5.5902,417000.0,NEAR OCEAN,7.010127,0.139762,2.516456,1

In [24]:
# Setting the y values.
y_train = df_train.above_average.values
y_val = df_val.above_average.values
y_test = df_test.above_average.values

In [25]:
del df_train["above_average"]
del df_val["above_average"]
del df_test["above_average"]

del df_train["median_house_value"]
del df_val["median_house_value"]
del df_test["median_house_value"]

In [26]:
df_numerical = df.drop(columns="ocean_proximity")

In [27]:
## Correlation matrix

corr_matrix = df_numerical.corr()
corr_matrix

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,rooms_per_household,bedrooms_per_room,population_per_household,above_average
longitude,1.000000,-0.924664,-0.108197,0.044568,0.068082,0.099773,0.055310,-0.015176,-0.045967,-0.027540,0.084836,0.002476,-0.072633
latitude,-0.924664,1.000000,0.011173,-0.036100,-0.065318,-0.108785,-0.071035,-0.079809,-0.144160,0.106389,-0.104112,0.002366,-0.098810
housing_median_age,-0.108197,0.011173,1.000000,-0.361262,-0.317063,-0.296244,-0.302916,-0.119034,0.105623,-0.153277,0.125396,0.013191,0.080069
total_rooms,0.044568,-0.036100,-0.361262,1.000000,0.920196,0.857126,0.918484,0.198050,0.134153,0.133798,-0.174583,-0.024581,0.128782
total_bedrooms,0.068082,-0.065318,-0.317063,0.920196,1.000000,0.866266,0.966507,-0.007295,0.049148,0.002717,0.122205,-0.028019,0.056209
population,0.099773,-0.108785,-0.296244,0.857126,0.866266,1.000000,0.907222,0.004834,-0.024650,-0.072213,0.031397,0.069863,-0.014898
households,0.055310,-0.071035,-0.302916,0.918484,0.966507,0.907222,1.000000,0.013033,0.065843,-0.080598,0.059818,-0.027309,0.074778
median_income,-0.015176,-0.079809,-0.119034,0.198050,-0.007295,0.004834,0.013033,1.000000,0.688075,0.326895,-0.573836,0.018766,0.541778
median_house_value,-0.045967,-0.144160,0.105623,0.134153,0.049148,-0.024650,0.065843,0.688075,1.000000,0.151948,-0.238759,-0.023737,0.804353
rooms_per_household,-0.027540,0.106389,-0.153277,0.133798,0.002717,-0.072213,-0.080598,0.326895,0.151948,1.000000,-0.387465,-0.004852,0.112104
bedrooms_per_room,0.084836,-0.104112,0.125396,-0.174583,0.122205,0.031397,0.059818,-0.573836,-0.238759,-0.387465,1.000000,0.003047,-0.211781
population_per_household,0.002476,0.002366,0.013191,-0.024581,-0.028019,0.069863,-0.027309,0.018766,-0.023737,-0.004852,0.003047,1.000000,-0.023354
above_average,-0.072633,-0.098810,0.080069,0.128782,0.056209,-0.014898,0.074778,0.541778,0.804353,0.112104,-0.211781,-0.023354,1.000000

Question 3

Calculate the mutual information score between above_average and ocean_proximity . Use the training set only.

Round it to 2 decimals using round(score, 2)

What is their mutual information score?

In [28]:
df_full_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 14196 to 15795
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   longitude                 16512 non-null  float64
 1   latitude                  16512 non-null  float64
 2   housing_median_age        16512 non-null  float64
 3   total_rooms               16512 non-null  float64
 4   total_bedrooms            16512 non-null  float64
 5   population                16512 non-null  float64
 6   households                16512 non-null  float64
 7   median_income             16512 non-null  float64
 8   median_house_value        16512 non-null  float64
 9   ocean_proximity           16512 non-null  object
 10  rooms_per_household       16512 non-null  float64
 11  bedrooms_per_room         16512 non-null  float64
 12  population_per_household  16512 non-null  float64
 13  above_average             16512 non-null  int64
dtypes: float64(12), int64(1), object(1)
memory usage: 1.9+ MB

In [29]:
mutual_score = mutual_info_score(df_full_train.above_average,df_full_train.ocean_proximity)

In [30]:
round(mutual_score,2)

0.1


Question 4

Now let's train a logistic regression

Remember that we have one categorical variable ocean_proximity in the data. Include it using one-hot encoding
.
Fit the model on the training dataset.

To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:

model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)

Calculate the accuracy on the validation dataset and round it to 2 decimal digits.

In [31]:
train_dicts =df_train.to_dict(orient = 'records')

In [32]:
dv = DictVectorizer(sparse = False)

In [33]:
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [34]:
dv.get_feature_names_out()

array(['bedrooms_per_room', 'households', 'housing_median_age',
       'latitude', 'longitude', 'median_income',
       'ocean_proximity=<1H OCEAN', 'ocean_proximity=INLAND',
       'ocean_proximity=ISLAND', 'ocean_proximity=NEAR BAY',
       'ocean_proximity=NEAR OCEAN', 'population',
       'population_per_household', 'rooms_per_household',
       'total_bedrooms', 'total_rooms'], dtype=object)

In [35]:
val_dict = df_val.to_dict(orient='records')
X_val = dv.transform(val_dict)

In [36]:
dv.get_feature_names()

C:\Users\User\anaconda3\Newfolder\envs\ml-zoomcamp\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['bedrooms_per_room',
 'households',
 'housing_median_age',
 'latitude',
 'longitude',
 'median_income',
 'ocean_proximity=<1H OCEAN',
 'ocean_proximity=INLAND',
 'ocean_proximity=ISLAND',
 'ocean_proximity=NEAR BAY',
 'ocean_proximity=NEAR OCEAN',
 'population',
 'population_per_household',
 'rooms_per_household',
 'total_bedrooms',
 'total_rooms']

In [37]:
X_train = dv.fit_transform(train_dicts)

In [38]:
X_train.shape

(12384, 16)

In [39]:
model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [40]:
# Hard predictions
y_pred =model.predict(X_val)

In [41]:
# Bias 
model.intercept_[0]

-0.1598237246697497

In [42]:
# Weights
model.coef_[0].round(3)

array([ 0.438,  0.004,  0.036,  0.136,  0.093,  1.216,  0.468, -1.729,
        0.046,  0.193,  0.863, -0.002,  0.01 , -0.014,  0.002, -0.   ])

In [43]:
above_average_decision = (y_pred >= 0.5)
above_average_decision

array([False, False,  True, ...,  True,  True, False])

In [44]:
# Calculating the accuracy of the model itself. 0.836, not bad! 
score =(y_val == above_average_decision).mean()

In [45]:
round(score,2)

0.84

Question 5

Let's find the least useful feature using the feature elimination technique.

Train a model with all these features (using the same parameters as in Q4).

Now exclude each feature from this set and train a model without it. Record the accuracy for each model.

For each feature, calculate the difference between the original accuracy and the accuracy without the feature.
Which of following feature has the smallest difference?

In [46]:
dv = DictVectorizer(sparse = False)

In [47]:


main_score = score
score_list = list()
columns = df_train.columns.to_list()
for col in columns:
    columns_list =columns.copy()
    columns_list.remove(col)
    
    train_dicts = df_train[columns_list].to_dict(orient="records")
    X_train = dv.fit_transform(train_dicts)
    
    ## Training the model
    model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    ## transforming the validation datasets
    val_dicts = df_val[columns_list].to_dict(orient="records")
    X_val = dv.transform(val_dicts)

    y_pred = model.predict(X_val)

    ## from sklearn
    new_score =accuracy_score(y_pred,y_val)
    score_list.append(new_score)
    
diff_table = {"feature":columns, "new_score":score_list}

In [48]:

diff_dict = {"feature":columns, "new_score":score_list}
diff_df = pd.DataFrame(diff_dict)
diff_df["diff"] = main_score - diff_df["new_score"]
diff_df.sort_values(by=["diff"]).reset_index(drop=True)

                     feature  new_score      diff
0   population_per_household   0.838178 -0.001938
1                total_rooms   0.837452 -0.001211
2        rooms_per_household   0.836967 -0.000727
3          bedrooms_per_room   0.835998  0.000242
4                  longitude   0.835756  0.000484
5             total_bedrooms   0.835514  0.000727
6                 households   0.833576  0.002665
7                   latitude   0.832849  0.003391
8         housing_median_age   0.832607  0.003634
9                 population   0.826308  0.009932
10           ocean_proximity   0.819767  0.016473
11             median_income   0.785610  0.050630

Answer 5

total_bedrooms

Question 6

For this question, we'll see how to use a linear regression model from Scikit-Learn

We'll need to use the original column 'median_house_value'. Apply the logarithmic transformation to this column.

Fit the Ridge regression model (model = Ridge(alpha=a, solver="sag", random_state=42)) on the training data.

This model has a parameter alpha. Let's try the following values: [0, 0.01, 0.1, 1, 10]
Which of these alphas leads to the best RMSE on the validation set? Round your RMSE scores to 3 decimal digits.

If there are multiple options, select the smallest alpha.

In [49]:
#Applying the logarithnmic transformation to the median_house_value
df['median_house_value']=np.log1p(df['median_house_value'])

In [50]:
#splitting the data into full_train and test with a random state 42
# and also splitting the full_train into train and validitation
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [51]:
# getting the y values
y_train = df_train.median_house_value.values
y_val = df_val.median_house_value.values
y_test = df_test.median_house_value.values

In [52]:
#deleting the target from the train,test and val
del df_train["median_house_value"]
del df_val["median_house_value"]
del df_test["median_house_value"]

In [53]:
#preparing data for training and testing
train_dicts =df_train.to_dict(orient = 'records')
dv = DictVectorizer(sparse = False)
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [54]:
X_train = dv.fit_transform(train_dicts)

In [55]:
val_dict = df_val.to_dict(orient='records')
X_val = dv.transform(val_dict)

In [56]:
mse = mean_squared_error

alpha_list = [0, 0.01, 0.1, 1, 10]

for a in alpha_list:
    model = Ridge(alpha=a, solver="sag", random_state=42)
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_val)
    
    score = np.sqrt(mse(y_pred, y_val))
        
    print(f"The score for alpha parameter {a} -- {round(score,3)}")

The score for alpha parameter 0 -- 0.524
The score for alpha parameter 0.01 -- 0.524
The score for alpha parameter 0.1 -- 0.524
The score for alpha parameter 1 -- 0.524
The score for alpha parameter 10 -- 0.524

Answer:
0